# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys4_ddr_constraints.xdc

# IP: ip/p2_motions_blue/p2_motions_blue.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p2_motions_blue || ORIG_REF_NAME==p2_motions_blue} -quiet] -quiet

# IP: ip/p2_motions_green/p2_motions_green.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p2_motions_green || ORIG_REF_NAME==p2_motions_green} -quiet] -quiet

# IP: ip/p2_motions_red/p2_motions_red.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p2_motions_red || ORIG_REF_NAME==p2_motions_red} -quiet] -quiet

# IP: ip/p2_motions/p2_motions.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p2_motions || ORIG_REF_NAME==p2_motions} -quiet] -quiet

# IP: ip/p1_motions_blue/p1_motions_blue.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p1_motions_blue || ORIG_REF_NAME==p1_motions_blue} -quiet] -quiet

# IP: ip/p1_motions_green/p1_motions_green.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p1_motions_green || ORIG_REF_NAME==p1_motions_green} -quiet] -quiet

# IP: ip/p1_motions_red/p1_motions_red.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p1_motions_red || ORIG_REF_NAME==p1_motions_red} -quiet] -quiet

# IP: ip/p1_motions/p1_motions.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p1_motions || ORIG_REF_NAME==p1_motions} -quiet] -quiet

# IP: ip/clk_wiz_final/clk_wiz_final.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_final || ORIG_REF_NAME==clk_wiz_final} -quiet] -quiet

# XDC: ip/p2_motions_blue/p2_motions_blue_ooc.xdc

# XDC: ip/p2_motions_green/p2_motions_green_ooc.xdc

# XDC: ip/p2_motions_red/p2_motions_red_ooc.xdc

# XDC: ip/p2_motions/p2_motions_ooc.xdc

# XDC: ip/p1_motions_blue/p1_motions_blue_ooc.xdc

# XDC: ip/p1_motions_green/p1_motions_green_ooc.xdc

# XDC: ip/p1_motions_red/p1_motions_red_ooc.xdc

# XDC: ip/p1_motions/p1_motions_ooc.xdc
