# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys4_ddr_constraints.xdc

# IP: ip/p1_at_rest_red/p1_at_rest_red.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p1_at_rest_red || ORIG_REF_NAME==p1_at_rest_red} -quiet] -quiet

# IP: ip/p1_at_rest_blue/p1_at_rest_blue.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==p1_at_rest_blue || ORIG_REF_NAME==p1_at_rest_blue} -quiet] -quiet

# IP: ip/clk_wiz_final/clk_wiz_final.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_final || ORIG_REF_NAME==clk_wiz_final} -quiet] -quiet
