#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 15 13:30:20 EST 2020
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim game_state_tb_behav -key {Behavioral:sim_1:Functional:game_state_tb} -tclbatch game_state_tb.tcl -view /afs/athena.mit.edu/user/d/i/dianah13/ddl/Game-Logic/game_logic/game_state_tb_behav.wcfg -log simulate.log"
xsim game_state_tb_behav -key {Behavioral:sim_1:Functional:game_state_tb} -tclbatch game_state_tb.tcl -view /afs/athena.mit.edu/user/d/i/dianah13/ddl/Game-Logic/game_logic/game_state_tb_behav.wcfg -log simulate.log

